run-with-local-db:
  image: urlable/redirect-api
  ports:
    - 8080:8080
  environment:
    - SHORT_URL_SVC_HOST=http://load-balance-svc.urlable-dev.5ecdac38.svc.dockerapp.io
    - SHORT_URL_SVC_PORT=80